config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  get 'persons/profile', as: 'user_root'
  root 'home#index'
  resources :videos

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :ifadm, only: [:destroy, :edit, :new, :create, :update]
  before_action :find_video_by_id, only: [:show, :edit, :update, :destroy]

  def index
    @videos = Video.all.order("created_at DESC")
  end
  def show
    @save = @video.content.to_s[0..11] + "ss" + @video.content.to_s[12..-1]
    if user_signed_in?
      if current_user.adm
        @adm = true
      end
    end
  end
  def new
    @video = Video.new
  end
  def edit
  end
  def update
    if @video.update(video_params)
      redirect_to videos_path
    else
      render params
    end
  end
  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to videos_path
    else
      render 'new'
    end
  end
  def destroy
    @video.destroy
    redirect_to videos_path
  end

  private
    def ifadm
      if user_signed_in?
        if current_user.adm
          @adm = true
        else
          redirect_to "/"
        end
      else
        redirect_to "/"
      end
    end

    def video_params
      params.require(:video).permit(:title, :content, :category)
    end

    def find_video_by_id
      @video = Video.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ru">

<head>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="home/assets/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa|Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>AVT-video</title>
</head>

<body>
    <div class="container-fluid hei">
        <nav class="transparent z">
            <div class="nav-wrapper p-r">
                <ul id="slide-out" class="side-nav">
                    <li>
                        <div class="userView"> <img class="background" src="home/assets/img/services/wedding.jpg">
                            <a href="#!user"><img class="circle" src="home/assets/img/services/anniversary.jpg"></a> <a href="#!name"><span class="white-text name">John Doe</span></a> <a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a> </div>
                    </li>
                    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
                    <li><a href="#!">Second Link</a></li>
                    <li>
                        <div class="divider"></div>
                    </li>
                    <li><a class="subheader">Subheader</a></li>
                    <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
                </ul> <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
                <a href="#" class="brand-logo center"><img src="home/assets/img/logo1.png" alt=""></a>
                <ul id="nav-mobile-l" class="left hide-on-med-and-down n-l">
                    <li><a href="sass.html">Обо мне</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a class="modal-trigger" href="#modal1">Контакты</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a href="collapsible.html">Услуги</a></li>
                </ul>
                <ul id="nav-mobile-r" class="right hide-on-med-and-down n-r">
                    <li><a href="sass.html">Прайс-лист</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a href="badges.html">Блог</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a href="<%= videos_path %>">Мои работы</a></li>
                    <% if user_signed_in? %>
                      <li class="user"> <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %> </li>
                      <li class="user"><a href="persons/profile"><%= current_user.email %></a></li>
                    <% else %>
                      <li class="user"> <%= link_to 'Войти', new_user_session_path %>
                      <li class="user"> <%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
                    <% end %>
                </ul>
            </div>
        </nav>
        <div id="modal1" class="modal modal-fixed-footer">
            <div class="modal-content">
                <h5>Вы можете связаться со мной одним из следующих способов:</h5>
                <div class="row">
                    <div class="col s4">
                        <div class="head"> <i class="material-icons medium">contact_phone</i>
                            <h6 class="contact">Моб. телефон</h6> </div>
                    </div>
                    <div class="col s4">
                        <div class="head"> <i class="material-icons medium">email</i>
                            <h6 class="contact">E-mail</h6> </div>
                    </div>
                    <div class="col s4">
                        <div class="head"> <i class="material-icons medium">group</i>
                            <h6 class="contact">Социальные сети</h6> </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer"> <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Закрыть</a> </div>
        </div>
        <div class="parallax-container hei header-parallax">
            <div class="parallax slider1"><img src="home/assets/img/bg.jpg"></div>
            <div class="parallax slider2"><img src="home/assets/img/bg2.jpg"></div>
            <div class="parallax slider3"><img src="home/assets/img/bg.jpg"></div>
            <div class="parallax slider4"><img src="home/assets/img/bg2.jpg"></div>
            <div class="parallax bg-black"></div>
        </div>
        <div class="title-cont">
            <div class="title"> <span class="name-custom">A<span class="v">V</span>T
                <br/>видео
                <br/> </span>
                <div class="under-title"> <span class="line"></span> <span class="text-descr">***Видеосъемка свадеб и торжеств***</span> <span class="line"></span> <span class="heart1">&#x2764;</span> <span class="heart2">&#x2764;</span> </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="fullscreen">
        <div class="container">
            <div class="post aboutme">
                <div class="title-post">
                    <h3><span class="heart-title">&#x2764;</span>Обо мне<span class="heart-title">&#x2764;</span></h3> <span class="line"></span> </div>
                <div class="body-post">
                    <div class="row">
                        <div class="col s12 m4"> <img class="z-depth-3" src="home/assets/img/IAM.jpg" alt="" class=""> </div>
                        <p class="body-title">Здравствуйте, уважаемый посетитель моего сайта!</p>
                        <p class="body-content">Очень непросто написать о себе… Сейчас в интернете столько продукта связанного с видеосъёмкой! Все норовят предложить свои услуги в «красивой упаковке», рассказывают какие они профи, и как творчески, извините, «креативно» подходят к видеосъёмке. Может быть с точки зрения продвижения на рынке услуг по видеосъёмке это верно, хотя на поверку очень часто вся «креативность» сводится к кадрам вне резкости и полету квадрокоптера, а самая большая «креативность» это, естественно, цена. Почему-то бытует мнение, что чем дороже видеосъёмка, тем она лучше. Эта странность требует, наверное, психологических исследований. Хотя, конечно, каждый выбирает по себе. На мой взгляд задача оператора (не люблю почему-то слово «видеограф», какое-то оно не настоящее), так вот, задача оператора — передать те чувства и эмоции, которые испытывали молодожёны и гости свадьбы в день торжества, чтобы сохранить их в свадебном фильме. Сохранить, а главное подчеркнуть. И тогда, сколько бы лет не прошло, вы всегда сможете вернуться не только мыслями, но и сердцами в один из самых главных в вашей семье дней! Мой лучший фильм о свадьбе ещё не снят. Я уверен, что мы с вами обязательно это сделаем!</p>
                        <p class="body-title">Видеосъемка в детских садах.</p>
                        <p class="body-content">Видеосъемкой я занимаюсь уже лет десять. Приходилось снимать разное видео. Каждая новая задача это новые эмоции, новые трудности, но и новый бесценный опыт, который нигде не купишь. Очень люблю снимать в детских садах. Вот где шквал эмоций! Непосредственность детей это стопроцентный плюс к фильму! Но чтобы дети приняли тебя за «своего» надо заслужить их доверие. А это очень непросто. Дети всегда чувствуют фальшь. Надо мыслить как они, разбудить в своей душе ребёнка и тогда отличные эмоциональные кадры станут настоящим украшением фильма, а родители увидят своего ребёнка в детском саду таким, какой он есть — озорным, весёлым, капризным, задумчивым и рассудительным, в общем — разным, но настоящим! А это, как я уже сказал выше, я и ценю больше всего в видеосъемке. Этот сайт создан для вашего удобства. Здесь представлены примеры моих работ, а также информация для связи со мной. Сайт постоянно совершенствуется. Информация об услугах обновляется. Надеюсь мои работы Вам понравятся, буду рад сотрудничеству</p>
                        <p class="body-title">С уважением, Андрей Тимошенко.</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="post services">
                <div class="title-post">
                    <h3><span class="heart-title">&#x2764;</span>Услуги<span class="heart-title">&#x2764;</span></h3> <span class="line"></span> </div>
                <div class="body-post">
                    <div class="row">
                        <div class="service col s12 m6 l3"> <img src="home/assets/img/services/wedding.jpg" alt="">
                            <p class="bg-service"> </p>
                            <div class="outline"></div>
                            <a href="" class=""> <span class="v-align"></span> <span class="service-title">Видеосъемка свадеб</span> </a>
                        </div>
                        <div class="service col s12 m6 l3"> <img src="home/assets/img/services/anniversary.jpg" alt="">
                            <p class="bg-service"> </p>
                            <div class="outline"></div>
                            <a href="" class=""> <span class="v-align"></span> <span class="service-title">Видеосъемка торжеств</span> </a>
                        </div>
                        <div class="service col s12 m6 l3"> <img src="home/assets/img/services/matinee.jpg" alt="">
                            <p class="bg-service"> </p>
                            <div class="outline"></div>
                            <a href="" class=""> <span class="v-align"></span> <span class="service-title">Видеосъемка утренников</span> </a>
                        </div>
                        <div class="service col s12 m6 l3"> <img src="home/assets/img/services/triumph.jpg" alt="">
                            <p class="bg-service"> </p>
                            <div class="outline"></div>
                            <a href="" class=""> <span class="v-align"></span> <span class="service-title">Видеосъемка выпускных</span> </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdn.rawgit.com/iserdmi/afterlag-js/2.0.2/dist/jquery.afterlag.min.js"></script>
    <script type="text/javascript" src="home/assets/js/all.js"></script>
    <script type="text/javascript" src="home/assets/js/slider.js"></script>
    <script type="text/javascript" src="home/assets/js/materialize.min.js"></script>
    <script>
        $.afterlag(function () {
            $('#loading').hide();
            Materialize.fadeInImage($('nav'));
            Materialize.fadeInImage($('.title-cont'));
        });
    </script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avtvideo</title>
  <link href="https://fonts.googleapis.com/css?family=Comfortaa|Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="loading"><img src="home/assets/img/loading.gif" alt=""></div>

<nav class="transparent z">
            <div class="nav-wrapper p-r">
                <ul id="slide-out" class="side-nav">
                    <li>
                        <div class="userView"> <img class="background" src="/home/assets/img/services/wedding.jpg">
                            <a href="#!user"><img class="circle" src="/home/assets/img/services/anniversary.jpg"></a> <a href="#!name"><span class="white-text name">John Doe</span></a> <a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a> </div>
                    </li>
                    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
                    <li><a href="#!">Second Link</a></li>
                    <li>
                        <div class="divider"></div>
                    </li>
                    <li><a class="subheader">Subheader</a></li>
                    <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
                </ul> <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
                <a href="/" class="brand-logo center"><img src="/home/assets/img/logo1.png" alt=""></a>
                <ul id="nav-mobile-l" class="left hide-on-med-and-down n-l">
                    <li><a href="sass.html">Обо мне</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a class="modal-trigger" href="#modal1">Контакты</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a href="collapsible.html">Услуги</a></li>
                </ul>
                <ul id="nav-mobile-r" class="right hide-on-med-and-down n-r">
                    <li><a href="sass.html">Прайс-лист</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a href="badges.html">Блог</a></li>
                    <li class="heart">&#x2764;</li>
                    <li><a href="collapsible.html">Мои работы</a></li>
                    <% if user_signed_in? %>
                      <li class="user"> <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %> </li>
                      <li class="user"><a href="persons/profile"><%= current_user.email %></a></li>
                    <% else %>
                      <li class="user"> <%= link_to 'Войти', new_user_session_path %>
                      <li class="user"> <%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
                    <% end %>
                </ul>
            </div>
        </nav>
        <div id="modal1" class="modal modal-fixed-footer">
            <div class="modal-content">
                <h5>Вы можете связаться со мной одним из следующих способов:</h5>
                <div class="row">
                    <div class="col s4">
                        <div class="head"> <i class="material-icons medium">contact_phone</i>
                            <h6 class="contact">Моб. телефон</h6> </div>
                    </div>
                    <div class="col s4">
                        <div class="head"> <i class="material-icons medium">email</i>
                            <h6 class="contact">E-mail</h6> </div>
                    </div>
                    <div class="col s4">
                        <div class="head"> <i class="material-icons medium">group</i>
                            <h6 class="contact">Социальные сети</h6> </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer"> <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Закрыть</a> </div>
        </div>
<%= yield %>

<script src="https://cdn.rawgit.com/iserdmi/afterlag-js/2.0.2/dist/jquery.afterlag.min.js"></script>


</body>
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Всякая информация</h5>
                <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni illo ut quod sint nostrum voluptatem natus ullam asperiores doloremque commodi eveniet eum totam quis accusantium odio a inventore, mollitia molestiae ratione. Tempora beatae nisi sed optio assumenda aliquid dignissimos vitae incidunt laborum. Illo blanditiis eos quas unde facilis asperiores, rem.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Новые видео</h5>
                <ul>
                    <% Video.all.order("created_at DESC").limit(4).each do |v| %>
                      <li><a class="grey-text text-lighten-3" href="<%= video_path(v) %>"><%= v.title %></a></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container"> © 2016 AVT-video <a class="grey-text text-lighten-4 right" href="#!">varsantim@rambler.ru</a> </div>
    </div>
</footer>
</html>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/videos/_form.html.erb
<div class="input-field">
  <%= label_tag(:video_title, "Название ролика") %>
  <%= text_field(:video, :title, class: "form-control") %>
</div>
<div class="row">
  <div class="input-field col s6">
    <%= label_tag(:video_content, 'Ссылка на видео с youtube.com') %>
    <%= text_field(:video, :content, class: "form-control") %>
  </div>
  <div class="input-field col s6">
    <%= select(:video, :category, options_for_select([["Свадьба"],["Досвадебное"],["Юбилей"],["Слайд-шоу"],["Выпускной"],["Детский сад"]])) %>
  </div>
</div>

app/views/videos/edit.html.erb
<div class="bg-nav"></div>
<div class="m-top container">
  <h2>Редактирование видео</h2>
  <%= form_for :video, url: video_path(@video), method: :patch do |f| %>
    <%= render 'form' %>
    <div class="form-group">
      <%= f.submit 'Сохранить изменения', :class => "form-control btn" %>
    </div>
  <% end %>
</div>

app/views/videos/index.html.erb
<div class="parallax-container">
    <div class="parallax"><img src="home/assets/img/bg2.jpg"></div>
    <h1>Мои работы</h1>
</div>
<% if user_signed_in? %>
  <% if current_user.adm %>
    <% @adm = 1 %>
  <% end %>
<% end %>
<div class="container rel">
  <% if @adm %>
    <a href="videos/new" class="btn-floating btn-large waves-effect waves-light red add-video"><i class="material-icons">add</i></a>
  <% end %>

  <div class="row">
  <% @videos.each do |video| %>
    <div class="col s12 m12 l6">
      <div class="card">
        <div class="card-image">
          <iframe width="100%" height="315" src="<%= video.content %>" frameborder="0" allowfullscreen></iframe>    
        </div>
        <div class="card-content">
          <p><%= video.title %></p>
        </div>
        <div class="card-action">
          <%= link_to 'Открыть', video_path(video) %>
          <% if @adm %>
            <%= link_to 'Редактировать', edit_video_path(video) %>
            <%= link_to 'Удалить', video_path(video), method: :delete, data:{confirm: "Удалить '#{video.title}'?"} %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="bg-nav">
</div>
<div class="m-top container">
  <h2>Новое видео</h2>
  <%= form_for :video, url: videos_path do |f| %>
    <%= render 'form' %>
    <div class="form-group">
      <%= f.submit 'Добавить видеоролик', :class => "form-control btn" %>
    </div>
  <% end %>
</div>

app/views/videos/show.html.erb
<div class="bg-nav"></div>
<div class="m-top rel container">
<% if @adm %>
  <div class="edit-video-btn fixed-action-btn horizontal">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">menu</i>
    </a>
    <ul>
      <li><a data-confirm="Удалить '<%= @video.title %>'" rel="nofollow" data-method="delete" href="/videos/<%= @video.id %>" class="btn-floating red darken-1"><i class="material-icons">delete_forever</i></a></li>
      <li><a href="/videos/<%= @video.id %>/edit" class="btn-floating yellow darken-1"><i class="material-icons">edit</i></a></li>
      <li><a href="<%= @save  %>" class="btn-floating blue darken-1"><i class="material-icons">file_download</i></a></li>
    </ul>
  </div>
<% end %>
  <div class="col s12 m12 l6">
  <div class="card">
    <div class="card-image">
      <iframe width="100%" height="500" src="<%= @video.content %>" frameborder="0" allowfullscreen></iframe>    
    </div>
    <div class="card-content">
      <p><%= @video.title %></p>
    </div>
  </div>
  </div>
</div>